print("\nmultiplos de 5")
cont1=0
for x in range (10+1,100):
    if x%5==0:
        print(x,end=",")
        cont1=cont1+1
print("\nlos numeros multiplos de 5 son en total :",cont1)

print("--------------------------------------------------------------")
print("\nmultiplos 3")
cont2=0
for x in range(10+1,100):    
    if x%3==0:
        print(x,end=",")
        cont2=cont2+1
print("\nlos numeros multiplos de 3 son en total :",cont2)
 

